<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { format_num, MaterialCard, Structure } from '$lib'
  import { download, fetch_zipped, mp_build_bucket } from '$lib/mp-api'

  let { data = $bindable() } = $props()

  let input_value = $state(`mp-${page.params.slug}`)
  let mp_id = $derived(input_value.trim().toLowerCase())
  let href = $derived(`https://materialsproject.org/materials/${mp_id}`)
  let aws_url = $derived(`${mp_build_bucket}/summary/${mp_id}.json.gz`)
</script>

<main>
  <center style="margin: 1em 0">
    <h1>
      Materials Explorer - {data.summary.formula_pretty}
      <span style="font-weight: lighter">(<a {href}>{mp_id}</a>)</span>
    </h1>

    <input
      placeholder="Enter MP material ID"
      bind:value={input_value}
      onkeydown={async (event) => {
        if (event.key === `Enter`) {
          goto(`/${mp_id}`)
          data.summary = await fetch_zipped(aws_url)
        }
      }}
    />
    <button
      onclick={async () => {
        goto(`/${mp_id}`)
        data.summary = await fetch_zipped(aws_url)
      }}
    >
      Fetch material
    </button>
    <span class="download">
      <button>Save material summary</button>
      <div>
        <button
          onclick={() => {
            if (!data.summary) return alert(`No data to download`)
            download(
              JSON.stringify(data.summary, null, 2),
              `${mp_id}.json`,
              `application/json`,
            )
          }}
        >
          JSON
        </button>
        <button
          onclick={async () => {
            const blob = await fetch_zipped(aws_url, { unzip: false })
            if (!blob) return
            download(blob, `${mp_id}.json.gz`, `application/gzip`)
          }}
        >
          Zipped JSON
        </button>
      </div>
    </span>
  </center>
  <Structure structure={data.summary.structure} />

  <MaterialCard material={data.summary} />

  <h3>
    Crystal description
    <small>
      (generated by <a
        href="https://github.com/hackingmaterials/robocrystallographer"
      >Robocrystallographer
      </a>)
    </small>
  </h3>
  <p>{data.robocrys.description}</p>

  <h2>Similar structures</h2>
  <ol class="similar-structures">
    {#each data?.similarity?.sim?.slice(0, 6) ?? [] as
      { task_id, dissimilarity, formula }
      (task_id + formula + dissimilarity)
    }
      <li>
        <strong>
          <a href="https://materialsproject.org/tasks/{task_id}">{task_id}</a>
        </strong>
        <span>{formula}</span>
        <br />
        <small>dissimilarity: {format_num(dissimilarity)}</small>
      </li>
    {:else}
      <li>No similar structures found</li>
    {/each}
  </ol>
</main>

<style>
  .download {
    position: relative;
  }
  .download div {
    display: none;
    position: absolute;
    top: 100%;
    left: 0;
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
  }
  .download div::before {
    /* increase top hover area */
    content: '';
    position: absolute;
    top: -6pt;
    left: 0;
    width: 100%;
    height: 100%;
  }
  .download:hover div {
    display: grid;
    gap: 3pt;
    opacity: 1;
    background-color: rgba(255, 255, 255, 0.12);
    margin: 4pt 0 0;
    padding: 3pt;
    border-radius: 3pt;
  }
  .download button {
    z-index: 1;
  }
  .similar-structures {
    display: flex;
    justify-content: space-around;
    flex-wrap: wrap;
    gap: 1em;
  }
  ol {
    list-style: none;
    text-align: center;
  }
  ol li span {
    font-weight: lighter;
    margin-left: 1em;
  }
</style>
