name: GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: janosh/workflows/.github/workflows/deno-gh-pages.yml@main
    with:
      deno-version: 2.3.7
