name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    uses: janosh/workflows/.github/workflows/deno-test.yml@main
    with:
      test-cmd: deno task vitest
      e2e-install-cmd: npx playwright install chromium
      e2e-test-cmd: npx playwright test
      deno-version: 2.3.7
      e2e-continue-on-error: true
