name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    uses: janosh/workflows/.github/workflows/deno-test.yml@main
    with:
      test-cmd: deno task unit
      e2e-test-cmd: deno task e2e
